# Generated by Django 4.2 on 2023-06-14 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None, null=True)),
                ('asset', models.TextField(default=None, null=True)),
                ('available', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('blocked', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None, null=True)),
                ('asset', models.TextField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('type', models.TextField(default=None, null=True)),
                ('description', models.TextField(blank=True, default=None)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Aproved')], default='P', max_length=1)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('id_transaction', models.TextField(blank=True, default=None, null=True)),
                ('parent_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backend.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalUserBalance',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.TextField(default=None, null=True)),
                ('asset', models.TextField(default=None, null=True)),
                ('available', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('blocked', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical user balance',
                'verbose_name_plural': 'historical user balances',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalTransaction',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('user', models.TextField(default=None, null=True)),
                ('asset', models.TextField(default=None, null=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0.0, max_digits=20)),
                ('type', models.TextField(default=None, null=True)),
                ('description', models.TextField(blank=True, default=None)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Aproved')], default='P', max_length=1)),
                ('datetime', models.DateTimeField(blank=True, editable=False)),
                ('id_transaction', models.TextField(blank=True, default=None, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_transaction', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.transaction')),
            ],
            options={
                'verbose_name': 'historical transaction',
                'verbose_name_plural': 'historical transactions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
