# Generated by Django 4.2 on 2023-07-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_parent_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltransaction',
            name='origin',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin',
            field=models.TextField(default=None, null=True),
        ),
    ]
